name: trm
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - expat=2.7.3=h982b769_0
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - adam-atan2==0.0.3
      - altair==6.0.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - argdantic==1.3.3
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - coolname==2.2.0
      - cycler==0.12.1
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - filelock==3.20.0
      - flask==3.1.2
      - fonttools==4.61.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.4
      - hydra-core==1.3.2
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - narwhals==2.13.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numba==0.62.1
      - numpy==2.2.6
      - omegaconf==2.3.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - platformdirs==4.5.0
      - protobuf==6.33.1
      - pyarrow==22.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydeck==0.9.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - scipy==1.15.3
      - sentry-sdk==2.44.0
      - setuptools-scm==9.2.2
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - streamlit==1.52.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tomli==2.3.0
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchvision==0.24.1
      - tornado==6.5.3
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.23.0
      - werkzeug==3.1.4
prefix: /opt/anaconda3/envs/trm
